### ISSUE TITLE
xamarin.forms.xaml.design and xamarin.forms.core.design missing

### ISSUE THREAD

**Issue by TheBigRic** [jamesmontemagno/MyShoppe#11]
I downloaded the complete source and hit F6. Unfortunately the build fails because there are several assemblies missing:

- Xamarin.Forms.Core.Design (hintpath is packages\Xamarin.Forms.2.0.1.6505\...)
- Xamarin.Forms.Xaml.Design (hintpath is packages\Xamarin.Forms.2.0.1.6505\...)

and some other SQL lite assemblies for windows phone, but I did not investigate yet why these are missing.

I looked in the packages folder and indeed the \Design folder is missing. Looking in the NuGet package the files are also missing. Even when I download the package (the referenced version) directly from NuGet these files are missing.

However the latest stable version does include this files. So I'm wondering how this could build with this version, or did NuGet remove these files from the package from some reason? 

We upgraded the package to the latest stable version, and after manually removing the references to the 2.0.1.6505 hintpath and reentering the references to the new packages most build errors where gone. 

The SQLite.WP80 and WP81 are referenced from some kind of SDK? Where can I download and install this??

**Comment by jamesmontemagno** [comment]
Fixed up.
For UWP you need to install the SQLite extension from "Extensions and Updates"

**Comment by TheBigRic** [comment]
Thank you for all the effort. Unfortunately after trying for a couple of hours I can't get this working using VS 2015. 
The reference for Bing Maps isn't working, although installed this using extension and updates. 

The reference 'Microsoft Visual C++ 2013 Runtime Package for Windows' makes me think you use VS2013?

**Comment by jamesmontemagno** [comment]
Hmmmm, shouldn't be I used 2015 on Windows 10. I will double check the UWP one isn't done though.

**Comment by TheBigRic** [comment]
It's all a bit strange. After uninstalling Bing Maps and MS visual studio runtime package. Rebooting my machine, reinstalling, rebooting VS, the Android and UWP now runs. Didn't try IOS as I have no access to my remote compiler machine at the moment. 

Although it runs, I still get build errors on the PCL for the FeedBackpage.xaml and StoresPages.xaml. And several warnings that not all NuGet package where successfully restored. However all references are without warning.

And while it runs, in the UWP version, when you press a store to go the details of a store an error occurs. This works in the Android version. 
Debugging this throws somewhere out of the solution and the stacktrace isn't helping also. Am I missing something else?

**Comment by TheBigRic** [comment]
After some further debugging I found that the Map control is causing the exception (Value cannot be null). The stack trace is:

>    at System.StubHelpers.HStringMarshaler.ConvertToNativeReference(String managed, HSTRING_HEADER* hstringHeader)
   at Windows.UI.Xaml.Controls.Maps.MapControl.put_MapServiceToken(String value)
   at Xamarin.Forms.Maps.UWP.MapRenderer.<OnElementChanged>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

The unhandledexception event handler is generated only in Debug mode, so you would think that in Release mode the app would jst crash, but it doesn't! In release it runs perfectly.
